### ISSUE TITLE
Small issue with installer and exe.xml autostart

### ISSUE THREAD

**Issue by sushiat** [ResetXPDR/MSFS2020_AutoFPS#1]
Hi, I had the windows store version way back when in 2020 on the game pass trial but ended up buying it on steam in the end. Thing is that your installer seems to find the old windows store "remains" (never really bother cleaning it all up) and modifies that exe.xml file but then stops and doesn't touch my steam file.

I know I should clean it up, but just in case someone is crazy enough to have both, it wouldn't hurt to just always check both locations - just in case.

**Comment by ResetXPDR** [comment]
I hadn't touched the installer code I inherited for this app yet, but looking into it I see that it tries the MS Store version first then Steam version if it didn't find the MS Store version. For the next release I have changed the order around so that Steam is checked first and MS Store is second, which should fix your issue. I have not set it to modify two possible installations as it should be extremely unlikely that someone went from the Steam version to the MS Store version (but in the world of programming, you never know for sure!) as it is far more likely that someone did what you did ie. trialed it on game pass then bought it outright. Thanks for letting me know!
