### ISSUE TITLE
ASK FOR UPDATING EXISTING MOBIFLIGHT MODULE ON INSTALL

### ISSUE THREAD

**Issue by fabianovm** [ResetXPDR/MSFS2020_AutoFPS#12]
Hello again my friend! Let me tell you, I use a lot of mobiflight devices, but I am still on mobiflight version 9.7 because it is the best that works on my setup. This version of mobiflight, installs a version 0.6.0 of the mobiflight event module on community folder. And all works ok...

When I installed MSFS2020_AUTOFPS or DynamicLOD, they update the mobiflight event module to latest version, which messes all with my cockpit. So, everytime I install MSFS2020_AUTOFPS or DynamicLOD, after installation I have to revert my mobiflight event module in community to old version again. and it works perfect with mobiflight and with MSFS2020_AUTOFPS or DynamicLOD.

**Suggestion: in installation, if a mobiflight module is found on community, ASK FIRST if user wants to update it.** In my case, latest mobiflight gives me error with my panels, with stredeck plugins for msfs, and more. So, if possible, ask in instalation before updating the mobiflight module to latest.

thanks a lot, all info here is to make the app better and better! thanks again, best regards!

**Comment by ResetXPDR** [comment]
Unfortunately, I have had many more issues with people running older versions of MobiFlight than the latest one so I am loath give all users the option of staying with such older versions and inviting even more issues because of it. As such, I will leave it as it is and, for users like yourself, at least there is a workaround that you can change back MobiFlight versions manually after installing one of my app updates, of which they should be less frequent in future now that most functionality has matured.

**Comment by fabianovm** [comment]
I, again, totally understand and respect your point of view, and in my case the 0.6.0 version of mobiflight wasm event module works perfect with my mobiflight 10 arduinos panels, lots of encoders, lcds, motorized trim wheel, really a lot. Also works with axis and ohms, with flight tracker a streamdeck plug-in, works with dynamiclod, and until now with msfs2020autofps.

The last mobilight wasm module for me gives panel errors, needs a lot of hard work to convert into last version and try to solve. The flighttacker plug-in also does not work on last.

So for now I will still keep the old one 0.6.0 with my workaround copying manually every msfs2020autofps update, no problem. 

Regards and many thanks for the amazing app @ResetXPDR !
