### ISSUE TITLE
I think I finally found the cause of the CTD.

### ISSUE THREAD

**Issue by ddobagi810** [ResetXPDR/MSFS2020_AutoFPS#39]
hello.
First of all, I apologize for my bad English. Please understand.
In the past, I've written that after a flight, when I come back to the world map
simconnect doesn't change from red text to green and CTD occurs after a few seconds. Do you remember that?

I reinstalled the sim today after reformatting Windows and wanted to take this opportunity to find out which addons and conflicts I had, so I started the tedious task of going through them one by one. 
I just found out the cause.

DLSS Swapper was the problem.
The default DLSS version of MSFS is 2.4.12.0.
I was using DLSS Swapper and was using version 3.5.1.

So I did about 10 rounds of testing.

DLSS 3.5.1 or 3.6 (the version I used)
MSFS run 15 times -> Airport loading -> World map : 15 times CTD.
 
DLSS 2.4.12.0 (default)
14 times MSFS run -> Airport loading -> World map : 14 times no problem.

You don't have all the addons installed yet.
However, the DLSS files I replaced with DLSS Swapper seem to have an impact.

Thank you for a great addon.

**Comment by ResetXPDR** [comment]
Thanks for letting me know. It is interesting because I have used DLSS 3.5.10 for pretty much the entire app development and testing phase and I recently updated to 3.6.0 with no negative effects. The DLSS version really shouldn't have any effect on the app interacting with MSFS, but your experience says otherwise. In any case, I'm glad you found a solution to your CTDs.
