### ISSUE TITLE
0.4.2.6 (test)  Stutters and MSFS Freezes

### ISSUE THREAD

**Issue by fppilot** [ResetXPDR/MSFS2020_AutoFPS#41]
Two observations here. My stutter issues appears to be caused when AutoFPS is sitting as the active Window above a running MSFS.  If I use the AutoFPS   "◙ On Top"  selection and then click back on MSFS to make it the active window, then desired behavior returns.

Regarding MSFS freezing up.  This has happened to terminate my last three flights, consecutively.  All three instances appear to share one characteristic.  I was at the time within perhaps one to two thousand feet of the tops of cloud layers and had the AutoFPS  "◙ Decrease Cloud Quality"  selected.  The first two instances were on climb out once breaking out on top.  The third instance was on descent when nearing the tops of a cloud layer.  The altitude on climb out from from the same airport at strikingly the same location in my flight plan.  Altitude was in the range of 26~28,000.   The instance on descent occurred at around 6,000 ft.  Here are the remainder of my settings.  I am on an RTX 3080 and also have the <4 RTX frame generation mod in use.  My FPS Sensitivity may have been set to 5.

![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/71080619/b3418562-f728-4dbf-a4bb-14595e084c04)

**Comment by ResetXPDR** [comment]
If you are getting stutters with AutoFPS with the focus, tick Pause when MSFS loses Focus to stop the app trying to control MSFS settings during that time.

Decrease cloud quality only reduces cloud quality if your TLOD is at TLOD Min and your FPS is below target FPS, ie as a last ditch effort to regain FPS, otherwise it is doing nothing being enabled. If the triggering of cloud quality reduction as previously mentioned is causing freezes/lockups, uncheck Decrease Cloud Quality as you have done, but if the aforementioned conditions were not being met then this was not the cause.
