### ISSUE TITLE
Message Default Settings 

### ISSUE THREAD

**Issue by Deltaflight84** [ResetXPDR/MSFS2020_AutoFPS#47]
Sometimes when i'm in flight appears me one message windows of MSFS2020 if i want to reset to default the graphics settings. Any advice?

**Comment by ResetXPDR** [comment]
Never seen that one. Can you please post a screenshot of what you are seeing when you get this message.

**Comment by Deltaflight84** [comment]
Yeah of course, i did not screenshoot so if it happen again i will send you a screen

**Comment by ResetXPDR** [comment]
Do you only get this message when running AutoFPS or does it happen without it running?

**Comment by ResetXPDR** [comment]
The only thing I can find about this message is that it only happens when a controller button is pressed and the user fixed it by deleting all bindings and creating a new profile for that controller. It had nothing to do with any external program. See [here](https://forums.flightsimulator.com/t/msfs-warning-about-resetting-graphics-settings/619628).

**Comment by Deltaflight84** [comment]
great i will check that

**Comment by ResetXPDR** [comment]
As this issue seems unrelated to AutoFPS, I'm going to close it out.
