### ISSUE TITLE
Cant re-open the new version .16

### ISSUE THREAD

**Issue by Morst04** [ResetXPDR/MSFS2020_AutoFPS#62]
Hi
Just upgraded to .16. Can open onbe and then the program runs. Have tried to shut the program down in the windows task manager and a coimple re-boot of pc but when I then press the autofps icon it dont start. When I re-press it says "the program already runs"?

It works fine with .10 version.

Any suggetions?
Thank you for a fantastic program!!

Kind regards
Morten

**Comment by ResetXPDR** [comment]
I am not really understanding the issue. It works but then you are shutting the program down using windows task manager? Why don't you just let the app auto close when you exit MSFS or exit the app through the system tray icon?
Then you say it doesn't start and then say you get an error message saying program is already running, probably because it already is running and is just minimised in the system tray. 
All I can suggest is looking in the system tray for the icon to be there when you first start it. If the main window isn't showing, double click on this system tray icon and it should appear. And don't ever use windows task manager to close it - right click the system tray icon.

**Comment by Morst04** [comment]
Thabk you. That worked. The system trat icon exit worked. Have a great Day. Best regardsMorten. Den 24. jun. 2024 kl. 10.26 skrev ResetXPDR ***@***.***>:﻿
I am not really understanding the issue. It works but then you are shutting the program down using windows task manager? Why don't you just let the app auto close when you exit MSFS or exit the app through the system tray icon?
Then you say it doesn't start and then say you get an error message saying program is already running, probably because it already is running and is just minimised in the system tray.
All I can suggest is looking in the system tray for the icon to be there when you first start it. If the main window isn't showing, double click on this system tray icon and it should appear. And don't ever use windows task manager to close it - right click the system tray icon.
